import type { Owner, Property, Tier } from "./types";
import { TIER_CLASSIC, TIER_PREMIUM } from "./tiers";

const IMG = {
  modernHouse: "1564013799919-ab600027ffc6",
  exteriorWhite: "1568605114967-8130f3a36994",
  interiorMinimal: "1502672260266-1c1ef2d93688",
  bedLuxury: "1522708323590-d24dbb6b0267",
  bathroom: "1571896349842-33c89424de2d",
  bedroomBright: "1505693416388-ac5ce068fe85",
  bedroomCozy: "1512918728675-ed5a9ecdebfd",
  livingRoom: "1571003123894-1f0594d2b5d9",
  kitchen: "1556909114-f6e7ad7d3136",
  apartment: "1600585154340-be6161a56a0c",
  loft: "1494526585095-c41746248156",
  balcony: "1545324418-cc1a3fa10c00",
  studyDesk: "1555854877-bab0e564b8d5",
};

const u = (id: string, w = 1400) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

// Every listing belongs to exactly one verified owner. There is no broker role.
export const OWNERS: Owner[] = [
  { id: "o1", name: "Meher D'Souza", since: 2022, verified: "verified", responseTime: "Usually replies in 1 hour", listings: 1 },
  { id: "o2", name: "Shridhar Rao", since: 2018, verified: "verified", responseTime: "Usually replies in 3 hours", listings: 1 },
  { id: "o3", name: "Anitha Reddy", since: 2019, verified: "verified", responseTime: "Usually replies in 2 hours", listings: 1 },
  { id: "o4", name: "Karthik Nair", since: 2021, verified: "verified", responseTime: "Usually replies in 4 hours", listings: 2 },
  { id: "o5", name: "Sridevi Menon", since: 2020, verified: "verified", responseTime: "Usually replies in 5 hours", listings: 1 },
  { id: "o6", name: "Vikram Mehta", since: 2019, verified: "verified", responseTime: "Usually replies in 2 hours", listings: 1 },
  { id: "o7", name: "Farah Sheikh", since: 2020, verified: "verified", responseTime: "Usually replies in 1 hour", listings: 1 },
  { id: "o8", name: "Rohit Khanna", since: 2026, verified: "pending", responseTime: "New owner — verification in progress", listings: 1 },
  { id: "o9", name: "Priya Joshi", since: 2021, verified: "verified", responseTime: "Usually replies in 3 hours", listings: 2 },
  { id: "o10", name: "Aman Khurana", since: 2020, verified: "verified", responseTime: "Usually replies in 2 hours", listings: 1 },
  { id: "o11", name: "Rajesh Verma", since: 2017, verified: "verified", responseTime: "Usually replies in 6 hours", listings: 1 },
  { id: "o12", name: "Neha Bansal", since: 2022, verified: "verified", responseTime: "Usually replies in 2 hours", listings: 1 },
  { id: "o13", name: "Reddy Family", since: 2017, verified: "verified", responseTime: "Usually replies in 4 hours", listings: 1 },
  { id: "o14", name: "Lakshmi Iyer", since: 2019, verified: "verified", responseTime: "Usually replies in 3 hours", listings: 1 },
];

const OWNER_MAP = new Map(OWNERS.map((o) => [o.id, o]));
export function getOwner(id: string): Owner | undefined {
  return OWNER_MAP.get(id);
}

// Property tier (Classic / Premium). Uses an explicit p.tier if set (e.g. by the
// owner/admin), otherwise derives a sensible default from furnishing + featured.
export function getTier(p: Property): Tier {
  return p.tier ?? (p.featured || p.furnishing === "Furnished" ? TIER_PREMIUM : TIER_CLASSIC);
}

export const PROPERTIES: Property[] = [
  // ─── Bengaluru (clustered for the map-radius demo) ───
  {
    id: "home-blr-01",
    slug: "arch-loft-indiranagar",
    name: "The Arch Loft",
    tagline: "1BHK loft on Indiranagar 12th Main",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "Indiranagar",
    rent: 38000,
    deposit: 152000,
    bedrooms: 1,
    bathrooms: 1,
    area: 720,
    furnishing: "Furnished",
    preferredTenants: "Anyone",
    availableFrom: "Immediately",
    rating: 4.9,
    reviews: 47,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Power backup", "Balcony"],
    images: [u(IMG.loft), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedLuxury), u(IMG.bathroom)],
    description:
      "Open-plan loft above a cafe on 12th Main. Tall arched windows, wood floors, small balcony. Minimum 11 month lease, ideal for a couple or working professional.",
    ownerId: "o1",
    highlights: ["11 month lease", "Fully furnished", "Balcony", "Pet friendly"],
    rules: ["No parties", "Quiet building"],
    coordinates: { lat: 12.9716, lng: 77.6411 },
    featured: true,
  },
  {
    id: "home-blr-02",
    slug: "jayanagar-bungalow-floor",
    name: "Jayanagar Bungalow Floor",
    tagline: "Independent 2BHK first floor on a 1962 bungalow",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "Jayanagar 4th Block",
    rent: 44000,
    deposit: 176000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "1 Jul 2026",
    rating: 4.7,
    reviews: 28,
    amenities: ["Wi-Fi", "Kitchen", "Covered parking", "Garden", "Power backup", "Independent entry"],
    images: [u(IMG.exteriorWhite), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedroomBright)],
    description:
      "First floor flat in an old bungalow with an independent staircase entry. Tall windows, mosaic flooring, guava tree in the garden. Families preferred.",
    ownerId: "o2",
    highlights: ["Independent entry", "Garden", "11 month lease"],
    rules: ["No pets", "Veg cooking preferred"],
    coordinates: { lat: 12.9281, lng: 77.5938 },
  },
  {
    id: "home-blr-03",
    slug: "koramangala-garden-2bhk",
    name: "Koramangala Garden 2BHK",
    tagline: "Bright 2BHK near Forum Mall",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "Koramangala 5th Block",
    rent: 55000,
    deposit: 220000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    furnishing: "Furnished",
    preferredTenants: "Anyone",
    availableFrom: "Immediately",
    rating: 4.8,
    reviews: 39,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Lift", "Gated society", "Power backup"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedroomBright), u(IMG.bathroom)],
    description:
      "Second floor 2BHK in a small gated block, 4 minute walk from Forum Mall. Modular kitchen, two balconies, covered parking included.",
    ownerId: "o3",
    highlights: ["Walk to Forum Mall", "Gated society", "Fully furnished"],
    rules: ["No smoking indoors", "11 month lease"],
    coordinates: { lat: 12.9352, lng: 77.6245 },
    featured: true,
  },
  {
    id: "home-blr-04",
    slug: "hsr-corner-3bhk",
    name: "HSR Corner 3BHK",
    tagline: "Spacious 3BHK in HSR Layout Sector 2",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "HSR Layout",
    rent: 60000,
    deposit: 300000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1450,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "15 Jul 2026",
    rating: 4.6,
    reviews: 21,
    amenities: ["Wi-Fi", "Kitchen", "Washing machine", "Covered parking", "Gym", "Lift", "Gated society", "Power backup"],
    images: [u(IMG.modernHouse), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedLuxury)],
    description:
      "Corner 3BHK on the 4th floor of a 2019 society building. Cross ventilation on three sides, two covered parking slots, gym in the basement.",
    ownerId: "o4",
    highlights: ["Corner unit", "Society gym", "2 parking slots"],
    rules: ["Family only", "No commercial use"],
    coordinates: { lat: 12.9116, lng: 77.6389 },
  },
  {
    id: "home-blr-05",
    slug: "bellandur-lake-view-3bhk",
    name: "Bellandur Lake View 3BHK",
    tagline: "Unfurnished 3BHK with lake-facing balcony",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "Bellandur",
    rent: 48000,
    deposit: 192000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1350,
    furnishing: "Unfurnished",
    preferredTenants: "Family",
    availableFrom: "Immediately",
    rating: 4.4,
    reviews: 16,
    amenities: ["Kitchen", "Covered parking", "Lift", "Gated society", "Power backup", "Children's play area"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.bedroomBright), u(IMG.kitchen)],
    description:
      "Lake-facing 3BHK in a large township off Outer Ring Road. Unfurnished so you can set it up your way. Walk to tech parks on ORR.",
    ownerId: "o4",
    highlights: ["Lake view", "Near ORR tech parks", "Play area"],
    rules: ["No pets in society", "11 month lease"],
    coordinates: { lat: 12.9259, lng: 77.6229 },
  },
  {
    id: "home-blr-06",
    slug: "whitefield-family-home",
    name: "Whitefield Family Home",
    tagline: "2BHK in a quiet Whitefield enclave",
    city: "Bengaluru",
    state: "Karnataka",
    neighborhood: "Whitefield",
    rent: 35000,
    deposit: 70000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1150,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "1 Aug 2026",
    rating: 4.5,
    reviews: 12,
    amenities: ["Wi-Fi", "Kitchen", "Covered parking", "Garden", "Power backup", "Gated society"],
    images: [u(IMG.exteriorWhite), u(IMG.livingRoom), u(IMG.bedroomCozy), u(IMG.kitchen)],
    description:
      "Ground floor 2BHK in a small villa enclave near ITPL. Private garden patch, covered parking, very quiet lane. Good for families with young kids.",
    ownerId: "o5",
    highlights: ["Private garden", "Near ITPL", "Quiet lane"],
    rules: ["Family only", "No loud music after 10 PM"],
    coordinates: { lat: 12.9698, lng: 77.75 },
  },

  // ─── Mumbai ───
  {
    id: "home-mum-01",
    slug: "bandra-bungalow-floor",
    name: "Bandra Bungalow Floor",
    tagline: "Heritage 2BHK on Pali Hill",
    city: "Mumbai",
    state: "Maharashtra",
    neighborhood: "Bandra West",
    rent: 95000,
    deposit: 570000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    furnishing: "Furnished",
    preferredTenants: "Family",
    availableFrom: "Immediately",
    rating: 4.8,
    reviews: 33,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Balcony"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedLuxury)],
    description:
      "First floor of a Pali Hill bungalow. Original Burma teak floors, mosaic tiles, jaali grilles, working fireplace. Gas geyser in both bathrooms.",
    ownerId: "o6",
    highlights: ["Heritage building", "Pali Hill", "Furnished", "12 month lease"],
    rules: ["No smoking", "12 month lease"],
    coordinates: { lat: 19.0644, lng: 72.8302 },
    featured: true,
  },
  {
    id: "home-mum-02",
    slug: "andheri-west-2bhk",
    name: "Andheri West 2BHK",
    tagline: "Semi-furnished 2BHK off Yari Road",
    city: "Mumbai",
    state: "Maharashtra",
    neighborhood: "Andheri West",
    rent: 65000,
    deposit: 195000,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    furnishing: "Semi-furnished",
    preferredTenants: "Anyone",
    availableFrom: "1 Jul 2026",
    rating: 4.6,
    reviews: 24,
    amenities: ["Wi-Fi", "AC", "Kitchen", "Washing machine", "Covered parking", "Lift", "Power backup"],
    images: [u(IMG.bedroomBright), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bathroom)],
    description:
      "Sixth floor 2BHK in a maintained society off Yari Road. 9 minute auto to Versova metro, walk to Lokhandwala market. Lift and 24x7 security.",
    ownerId: "o7",
    highlights: ["Near Versova metro", "24x7 security", "Lift"],
    rules: ["No overnight outside guests", "No smoking"],
    coordinates: { lat: 19.1197, lng: 72.8468 },
  },
  {
    id: "home-mum-03",
    slug: "powai-lake-2bhk",
    name: "Powai Lake 2BHK",
    tagline: "Furnished 2BHK with lake-facing windows",
    city: "Mumbai",
    state: "Maharashtra",
    neighborhood: "Powai",
    rent: 70000,
    deposit: 210000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1000,
    furnishing: "Furnished",
    preferredTenants: "Anyone",
    availableFrom: "Immediately",
    rating: 4.7,
    reviews: 18,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Gym", "Swimming pool", "Lift"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.bedLuxury), u(IMG.kitchen)],
    description:
      "Furnished 2BHK in a Hiranandani tower with lake-facing windows. Society pool and gym. Walk to Powai market and the lakeside promenade.",
    ownerId: "o8",
    highlights: ["Lake-facing", "Society pool + gym", "Hiranandani"],
    rules: ["No pets", "11 month lease"],
    coordinates: { lat: 19.1176, lng: 72.906 },
  },

  // ─── Pune ───
  {
    id: "home-pun-01",
    slug: "greens-at-kothrud",
    name: "Greens at Kothrud",
    tagline: "3BHK family home, 4 min walk to metro",
    city: "Pune",
    state: "Maharashtra",
    neighborhood: "Kothrud",
    rent: 52000,
    deposit: 156000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1400,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "Immediately",
    rating: 4.6,
    reviews: 22,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Gym", "Swimming pool", "Power backup"],
    images: [u(IMG.exteriorWhite), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedroomBright)],
    description:
      "3BHK on the 7th floor of a 2018 society building. Modular kitchen, two balconies, society pool and gym. 4 minute walk to the metro station.",
    ownerId: "o9",
    highlights: ["Walk to metro", "Society pool", "11 month lease"],
    rules: ["Veg only kitchen requested", "No pets"],
    coordinates: { lat: 18.5074, lng: 73.8077 },
  },
  {
    id: "home-pun-02",
    slug: "baner-hillside-2bhk",
    name: "Baner Hillside 2BHK",
    tagline: "Unfurnished 2BHK with hill-facing balcony",
    city: "Pune",
    state: "Maharashtra",
    neighborhood: "Baner",
    rent: 32000,
    deposit: 64000,
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    furnishing: "Unfurnished",
    preferredTenants: "Bachelors",
    availableFrom: "1 Jul 2026",
    rating: 4.4,
    reviews: 14,
    amenities: ["Kitchen", "Covered parking", "Lift", "Gated society", "Power backup"],
    images: [u(IMG.apartment), u(IMG.bedroomCozy), u(IMG.livingRoom)],
    description:
      "Unfurnished 2BHK on Baner hill with a balcony facing the slope. Close to IT offices on Baner Road. Bachelors welcome.",
    ownerId: "o9",
    highlights: ["Hill-facing balcony", "Near Baner IT", "Bachelors welcome"],
    rules: ["No loud parties", "11 month lease"],
    coordinates: { lat: 18.559, lng: 73.7868 },
  },

  // ─── Delhi NCR ───
  {
    id: "home-del-01",
    slug: "hauz-khas-studio",
    name: "Hauz Khas Studio",
    tagline: "Furnished studio with deer park view",
    city: "New Delhi",
    state: "Delhi",
    neighborhood: "Hauz Khas",
    rent: 42000,
    deposit: 84000,
    bedrooms: 1,
    bathrooms: 1,
    area: 560,
    furnishing: "Furnished",
    preferredTenants: "Anyone",
    availableFrom: "Immediately",
    rating: 4.7,
    reviews: 56,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Power backup", "Balcony"],
    images: [u(IMG.interiorMinimal), u(IMG.bedroomCozy), u(IMG.kitchen), u(IMG.livingRoom)],
    description:
      "Furnished studio above an art bookshop. Small kitchenette, foldout dining, balcony overlooking the deer park lake. Walk to Hauz Khas Village.",
    ownerId: "o10",
    highlights: ["Park view", "Furnished", "Walk to HKV"],
    rules: ["No loud guests", "No smoking"],
    coordinates: { lat: 28.5535, lng: 77.1939 },
  },
  {
    id: "home-del-02",
    slug: "saket-family-2bhk",
    name: "Saket Family 2BHK",
    tagline: "Semi-furnished 2BHK near Select Citywalk",
    city: "New Delhi",
    state: "Delhi",
    neighborhood: "Saket",
    rent: 47000,
    deposit: 141000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "1 Aug 2026",
    rating: 4.5,
    reviews: 19,
    amenities: ["Wi-Fi", "AC", "Kitchen", "Covered parking", "Lift", "Power backup", "Gated society"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.bedroomBright), u(IMG.kitchen)],
    description:
      "Second floor 2BHK in a residential lane. 6 minutes to Saket metro, 12 to Select Citywalk. Power backup and covered parking. Families preferred.",
    ownerId: "o11",
    highlights: ["Near Saket metro", "Covered parking", "Family friendly"],
    rules: ["Family only", "No smoking"],
    coordinates: { lat: 28.5245, lng: 77.2066 },
  },
  {
    id: "home-ggn-01",
    slug: "gurgaon-sector-54-3bhk",
    name: "Gurgaon Sector 54 3BHK",
    tagline: "High-floor 3BHK near Golf Course Road",
    city: "Gurugram",
    state: "Haryana",
    neighborhood: "Sector 54",
    rent: 58000,
    deposit: 174000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1600,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "Immediately",
    rating: 4.6,
    reviews: 17,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Covered parking", "Gym", "Swimming pool", "Lift", "Gated society"],
    images: [u(IMG.modernHouse), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedLuxury)],
    description:
      "High-floor 3BHK on Golf Course Road with rapid metro nearby. Club, pool and gym in the society. Two covered parking slots.",
    ownerId: "o12",
    highlights: ["Golf Course Road", "Club + pool", "Near rapid metro"],
    rules: ["No pets", "11 month lease"],
    coordinates: { lat: 28.4421, lng: 77.1025 },
  },

  // ─── Hyderabad ───
  {
    id: "home-hyd-01",
    slug: "banjara-garden-house",
    name: "Banjara Garden House",
    tagline: "Independent 3BHK with private courtyard",
    city: "Hyderabad",
    state: "Telangana",
    neighborhood: "Banjara Hills",
    rent: 78000,
    deposit: 234000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    furnishing: "Furnished",
    preferredTenants: "Family",
    availableFrom: "Immediately",
    rating: 4.8,
    reviews: 19,
    amenities: ["Wi-Fi", "AC", "Modular kitchen", "Washing machine", "Covered parking", "Garden", "Power backup"],
    images: [u(IMG.modernHouse), u(IMG.livingRoom), u(IMG.kitchen), u(IMG.bedLuxury), u(IMG.balcony)],
    description:
      "Independent ground floor with a walled courtyard. Marble flooring, large kitchen, three balconies. Pet friendly, families preferred.",
    ownerId: "o13",
    highlights: ["Independent floor", "Private garden", "Pet friendly"],
    rules: ["12 month lease", "No commercial use"],
    coordinates: { lat: 17.4133, lng: 78.4488 },
    featured: true,
  },

  // ─── Chennai ───
  {
    id: "home-che-01",
    slug: "alwarpet-verandah",
    name: "Alwarpet Verandah",
    tagline: "2BHK with a wraparound Madras verandah",
    city: "Chennai",
    state: "Tamil Nadu",
    neighborhood: "Alwarpet",
    rent: 46000,
    deposit: 92000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    furnishing: "Semi-furnished",
    preferredTenants: "Family",
    availableFrom: "1 Jul 2026",
    rating: 4.5,
    reviews: 14,
    amenities: ["Wi-Fi", "AC", "Kitchen", "Covered parking", "Balcony", "Power backup"],
    images: [u(IMG.apartment), u(IMG.livingRoom), u(IMG.bedroomBright), u(IMG.kitchen)],
    description:
      "Top floor 2BHK with red oxide flooring and a Madras-style verandah. Good cross ventilation, walk to Mylapore tank. Families preferred.",
    ownerId: "o14",
    highlights: ["Heritage flooring", "Cross ventilation", "Walk to Mylapore"],
    rules: ["No pets", "11 month lease"],
    coordinates: { lat: 13.0359, lng: 80.2532 },
  },
];

export const CITIES = Array.from(new Set(PROPERTIES.map((p) => p.city))).sort();
